name:                haskek
version:             0.1.0.0
github:              "githubuser/haskek"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskek#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp

library:
  source-dirs: src

executables:
  haskek-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskek

tests:
  haskek-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskek
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
